[processor.make]
exclude_files = ["Makefile"]

[processor.pyrefly]
enabled = false

[processor.markdownlint]
enabled = false

[processor.ascii_check]
enabled = false

[processor.a2x]
enabled = false

[processor.rumdl]
enabled = false

[processor.mdl]
enabled = false

[processor.slidev]
enabled = false

[processor.tidy]
enabled = false

[processor.htmlhint]
enabled = false

[processor.htmllint]
enabled = false

[processor.jslint]
enabled = false

[processor.jshint]
enabled = false

[processor.eslint]
enabled = false

[processor.stylelint]
enabled = false

[processor.standard]
enabled = false
