""" version which can be consumed from within the module """
VERSION_STR = "0.0.19"
DESCRIPTION = "Pytubekit will allow you to perform operations in your youtube account en masse"
APP_NAME = "pytubekit"
LOGGER_NAME = "pytubekit"
